export const CATEGORIES = {
    UNCATEGORIZED: { label: "Other" },
    UNCHECKED: { label: "Pending" },
    CHECKED: { label: "Done" },
    UNSUGGESTED: { label: "Other" },
    CONDIMENTS: { label: "Seasonings & condiments" },
    VEGETABLES: { label: "Vegetables" },
    FRUITS: { label: "Fruits" },
    CANNED: { label: "Canned goods" },
    FROZEN: { label: "Frozen foods" },
    DAIRY: { label: "Dairy" },
    CLEANERS: { label: "Cleaning supplies" },
    BAKERY: { label: "Bakery" },
    DELI: { label: "Deli" },
    SNACKS: { label: "Snack foods" },
    PASTA: { label: "Pasta" },
    SAUCES: { label: "Cooking sauces" },
    SEAFOOD: { label: "Fresh seafood" },
    MEAT: { label: "Fresh meat" },
    PERSONAL_CARE: { label: "Personal care" },
};
